### ISSUE TITLE
class suggestion Rana B.

### ISSUE THREAD

**Issue by Theseus33** [kbaque/music-mood-app#1]
I thought your project was cool, I love music so I really like the concept of playlist suggestions based on mood. The only thing I would have added is the ability to maybe play songs or create a youtube playlist based on the playlist. Overall it was a great project and the design was very clean.

**Comment by kbaque** [comment]
Thank you . I also thought the same about giving it the ability to actually play the song. The youtube playlist does sound like a good idea , I will be taking that into consideration.
